services:
  - type: cron
    name: radioacktiva_songs
    env: python
    plan: free
    schedule: "*/10000 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"